// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/loyalty/v1/merchantallocation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Merchantallocation records a daily Bucket C allocation for a merchant token.
type Merchantallocation struct {
	Key                          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Date                         string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Denom                        string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	ActivityScore                uint64 `protobuf:"varint,4,opt,name=activity_score,json=activityScore,proto3" json:"activity_score,omitempty"`
	BucketCAmount                uint64 `protobuf:"varint,5,opt,name=bucket_c_amount,json=bucketCAmount,proto3" json:"bucket_c_amount,omitempty"`
	StakersAmount                uint64 `protobuf:"varint,6,opt,name=stakers_amount,json=stakersAmount,proto3" json:"stakers_amount,omitempty"`
	TreasuryAmount               uint64 `protobuf:"varint,7,opt,name=treasury_amount,json=treasuryAmount,proto3" json:"treasury_amount,omitempty"`
	MerchantIncentiveStakersBps  uint64 `protobuf:"varint,8,opt,name=merchant_incentive_stakers_bps,json=merchantIncentiveStakersBps,proto3" json:"merchant_incentive_stakers_bps,omitempty"`
	MerchantIncentiveTreasuryBps uint64 `protobuf:"varint,9,opt,name=merchant_incentive_treasury_bps,json=merchantIncentiveTreasuryBps,proto3" json:"merchant_incentive_treasury_bps,omitempty"`
	Creator                      string `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Merchantallocation) Reset()         { *m = Merchantallocation{} }
func (m *Merchantallocation) String() string { return proto.CompactTextString(m) }
func (*Merchantallocation) ProtoMessage()    {}
func (*Merchantallocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_07b0723b68e1123b, []int{0}
}
func (m *Merchantallocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchantallocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchantallocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchantallocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchantallocation.Merge(m, src)
}
func (m *Merchantallocation) XXX_Size() int {
	return m.Size()
}
func (m *Merchantallocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchantallocation.DiscardUnknown(m)
}

var xxx_messageInfo_Merchantallocation proto.InternalMessageInfo

func (m *Merchantallocation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Merchantallocation) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Merchantallocation) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Merchantallocation) GetActivityScore() uint64 {
	if m != nil {
		return m.ActivityScore
	}
	return 0
}

func (m *Merchantallocation) GetBucketCAmount() uint64 {
	if m != nil {
		return m.BucketCAmount
	}
	return 0
}

func (m *Merchantallocation) GetStakersAmount() uint64 {
	if m != nil {
		return m.StakersAmount
	}
	return 0
}

func (m *Merchantallocation) GetTreasuryAmount() uint64 {
	if m != nil {
		return m.TreasuryAmount
	}
	return 0
}

func (m *Merchantallocation) GetMerchantIncentiveStakersBps() uint64 {
	if m != nil {
		return m.MerchantIncentiveStakersBps
	}
	return 0
}

func (m *Merchantallocation) GetMerchantIncentiveTreasuryBps() uint64 {
	if m != nil {
		return m.MerchantIncentiveTreasuryBps
	}
	return 0
}

func (m *Merchantallocation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Merchantallocation)(nil), "tokenchain.loyalty.v1.Merchantallocation")
}

func init() {
	proto.RegisterFile("tokenchain/loyalty/v1/merchantallocation.proto", fileDescriptor_07b0723b68e1123b)
}

var fileDescriptor_07b0723b68e1123b = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xbb, 0xf6, 0x9f, 0x0d, 0xd8, 0x4a, 0x50, 0x08, 0x2a, 0xb1, 0x08, 0x6a, 0x4f, 0x5b,
	0x8a, 0xbe, 0x80, 0x2d, 0x1e, 0x3c, 0x78, 0x69, 0x3d, 0x79, 0x59, 0xd2, 0x34, 0xd0, 0x65, 0xb7,
	0xc9, 0x92, 0x4c, 0x17, 0xf7, 0x2d, 0xbc, 0xf8, 0x4e, 0x1e, 0x7b, 0xf4, 0x28, 0xdd, 0x17, 0x91,
	0xcd, 0x6e, 0xaa, 0x50, 0x6f, 0x33, 0x1f, 0xdf, 0xfc, 0x12, 0x66, 0x90, 0x0f, 0x2a, 0x12, 0x92,
	0x2f, 0x59, 0x28, 0x87, 0xb1, 0xca, 0x58, 0x0c, 0xd9, 0x30, 0x1d, 0x0d, 0x57, 0x42, 0xf3, 0x25,
	0x93, 0xc0, 0xe2, 0x58, 0x71, 0x06, 0xa1, 0x92, 0x7e, 0xa2, 0x15, 0x28, 0x7c, 0xfa, 0xeb, 0xfb,
	0x95, 0xef, 0xa7, 0xa3, 0xab, 0x8f, 0x3a, 0xc2, 0xcf, 0x7b, 0x33, 0xf8, 0x18, 0xd5, 0x23, 0x91,
	0x11, 0xaf, 0xef, 0x0d, 0x3a, 0xd3, 0xa2, 0xc4, 0x18, 0x35, 0x16, 0x0c, 0x04, 0x39, 0xb0, 0xc8,
	0xd6, 0xf8, 0x04, 0x35, 0x17, 0x42, 0xaa, 0x15, 0xa9, 0x5b, 0x58, 0x36, 0xf8, 0x1a, 0x75, 0x19,
	0x87, 0x30, 0x0d, 0x21, 0x0b, 0x0c, 0x57, 0x5a, 0x90, 0x46, 0xdf, 0x1b, 0x34, 0xa6, 0x47, 0x8e,
	0xce, 0x0a, 0x88, 0x6f, 0x50, 0x6f, 0xbe, 0xe6, 0x91, 0x80, 0x80, 0x07, 0x6c, 0xa5, 0xd6, 0x12,
	0x48, 0xb3, 0xf4, 0x4a, 0x3c, 0x79, 0xb0, 0xb0, 0x88, 0x33, 0xc0, 0x22, 0xa1, 0x8d, 0xd3, 0x5a,
	0xa5, 0x56, 0xd1, 0x4a, 0xbb, 0x45, 0x3d, 0xd0, 0x82, 0x99, 0xb5, 0xce, 0x9c, 0xd7, 0xb6, 0x5e,
	0xd7, 0xe1, 0x4a, 0x9c, 0x20, 0xea, 0x96, 0x14, 0x84, 0x92, 0x0b, 0x09, 0x61, 0x2a, 0x02, 0xf7,
	0xc4, 0x3c, 0x31, 0xe4, 0xd0, 0xce, 0x9d, 0x3b, 0xeb, 0xc9, 0x49, 0xb3, 0xd2, 0x19, 0x27, 0x06,
	0x3f, 0xa2, 0xcb, 0x7f, 0x42, 0x76, 0x1f, 0x28, 0x52, 0x3a, 0x36, 0xe5, 0x62, 0x2f, 0xe5, 0xa5,
	0x92, 0x8a, 0x18, 0x82, 0xda, 0x5c, 0x0b, 0x06, 0x4a, 0x13, 0x64, 0x57, 0xe8, 0xda, 0xf1, 0xfd,
	0xe7, 0x96, 0x7a, 0x9b, 0x2d, 0xf5, 0xbe, 0xb7, 0xd4, 0x7b, 0xcf, 0x69, 0x6d, 0x93, 0xd3, 0xda,
	0x57, 0x4e, 0x6b, 0xaf, 0x67, 0x7f, 0x0e, 0xff, 0xb6, 0x3b, 0x3d, 0x64, 0x89, 0x30, 0xf3, 0x96,
	0xbd, 0xf5, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x2c, 0xfe, 0xb0, 0x1d, 0x02, 0x00,
	0x00,
}

func (m *Merchantallocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchantallocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchantallocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMerchantallocation(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if m.MerchantIncentiveTreasuryBps != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.MerchantIncentiveTreasuryBps))
		i--
		dAtA[i] = 0x48
	}
	if m.MerchantIncentiveStakersBps != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.MerchantIncentiveStakersBps))
		i--
		dAtA[i] = 0x40
	}
	if m.TreasuryAmount != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.TreasuryAmount))
		i--
		dAtA[i] = 0x38
	}
	if m.StakersAmount != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.StakersAmount))
		i--
		dAtA[i] = 0x30
	}
	if m.BucketCAmount != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.BucketCAmount))
		i--
		dAtA[i] = 0x28
	}
	if m.ActivityScore != 0 {
		i = encodeVarintMerchantallocation(dAtA, i, uint64(m.ActivityScore))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintMerchantallocation(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintMerchantallocation(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintMerchantallocation(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMerchantallocation(dAtA []byte, offset int, v uint64) int {
	offset -= sovMerchantallocation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Merchantallocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMerchantallocation(uint64(l))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovMerchantallocation(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovMerchantallocation(uint64(l))
	}
	if m.ActivityScore != 0 {
		n += 1 + sovMerchantallocation(uint64(m.ActivityScore))
	}
	if m.BucketCAmount != 0 {
		n += 1 + sovMerchantallocation(uint64(m.BucketCAmount))
	}
	if m.StakersAmount != 0 {
		n += 1 + sovMerchantallocation(uint64(m.StakersAmount))
	}
	if m.TreasuryAmount != 0 {
		n += 1 + sovMerchantallocation(uint64(m.TreasuryAmount))
	}
	if m.MerchantIncentiveStakersBps != 0 {
		n += 1 + sovMerchantallocation(uint64(m.MerchantIncentiveStakersBps))
	}
	if m.MerchantIncentiveTreasuryBps != 0 {
		n += 1 + sovMerchantallocation(uint64(m.MerchantIncentiveTreasuryBps))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMerchantallocation(uint64(l))
	}
	return n
}

func sovMerchantallocation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMerchantallocation(x uint64) (n int) {
	return sovMerchantallocation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Merchantallocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMerchantallocation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchantallocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchantallocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityScore", wireType)
			}
			m.ActivityScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivityScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketCAmount", wireType)
			}
			m.BucketCAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BucketCAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakersAmount", wireType)
			}
			m.StakersAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakersAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAmount", wireType)
			}
			m.TreasuryAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreasuryAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantIncentiveStakersBps", wireType)
			}
			m.MerchantIncentiveStakersBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MerchantIncentiveStakersBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantIncentiveTreasuryBps", wireType)
			}
			m.MerchantIncentiveTreasuryBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MerchantIncentiveTreasuryBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMerchantallocation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMerchantallocation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMerchantallocation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMerchantallocation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchantallocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMerchantallocation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMerchantallocation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMerchantallocation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMerchantallocation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMerchantallocation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMerchantallocation = fmt.Errorf("proto: unexpected end of group")
)
