// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/loyalty/v1/params.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	CreationMode            string `protobuf:"bytes,1,opt,name=creation_mode,json=creationMode,proto3" json:"creation_mode,omitempty"`
	DailyRollupTimezone     string `protobuf:"bytes,2,opt,name=daily_rollup_timezone,json=dailyRollupTimezone,proto3" json:"daily_rollup_timezone,omitempty"`
	TestnetTimelockHours    uint64 `protobuf:"varint,3,opt,name=testnet_timelock_hours,json=testnetTimelockHours,proto3" json:"testnet_timelock_hours,omitempty"`
	MainnetTimelockHours    uint64 `protobuf:"varint,4,opt,name=mainnet_timelock_hours,json=mainnetTimelockHours,proto3" json:"mainnet_timelock_hours,omitempty"`
	FeeSplitValidatorBps    uint64 `protobuf:"varint,5,opt,name=fee_split_validator_bps,json=feeSplitValidatorBps,proto3" json:"fee_split_validator_bps,omitempty"`
	FeeSplitTokenStakersBps uint64 `protobuf:"varint,6,opt,name=fee_split_token_stakers_bps,json=feeSplitTokenStakersBps,proto3" json:"fee_split_token_stakers_bps,omitempty"`
	FeeSplitMerchantPoolBps uint64 `protobuf:"varint,7,opt,name=fee_split_merchant_pool_bps,json=feeSplitMerchantPoolBps,proto3" json:"fee_split_merchant_pool_bps,omitempty"`
	SeizureOptInDefault     bool   `protobuf:"varint,8,opt,name=seizure_opt_in_default,json=seizureOptInDefault,proto3" json:"seizure_opt_in_default,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_63adabe37ef3b914, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCreationMode() string {
	if m != nil {
		return m.CreationMode
	}
	return ""
}

func (m *Params) GetDailyRollupTimezone() string {
	if m != nil {
		return m.DailyRollupTimezone
	}
	return ""
}

func (m *Params) GetTestnetTimelockHours() uint64 {
	if m != nil {
		return m.TestnetTimelockHours
	}
	return 0
}

func (m *Params) GetMainnetTimelockHours() uint64 {
	if m != nil {
		return m.MainnetTimelockHours
	}
	return 0
}

func (m *Params) GetFeeSplitValidatorBps() uint64 {
	if m != nil {
		return m.FeeSplitValidatorBps
	}
	return 0
}

func (m *Params) GetFeeSplitTokenStakersBps() uint64 {
	if m != nil {
		return m.FeeSplitTokenStakersBps
	}
	return 0
}

func (m *Params) GetFeeSplitMerchantPoolBps() uint64 {
	if m != nil {
		return m.FeeSplitMerchantPoolBps
	}
	return 0
}

func (m *Params) GetSeizureOptInDefault() bool {
	if m != nil {
		return m.SeizureOptInDefault
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "tokenchain.loyalty.v1.Params")
}

func init() {
	proto.RegisterFile("tokenchain/loyalty/v1/params.proto", fileDescriptor_63adabe37ef3b914)
}

var fileDescriptor_63adabe37ef3b914 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xc0, 0x73, 0xb4, 0x84, 0x72, 0x82, 0x01, 0xf7, 0x9f, 0x95, 0x4a, 0x26, 0x2a, 0x0c, 0x11,
	0x43, 0xac, 0xd2, 0xb2, 0x20, 0xa6, 0x8a, 0x01, 0x86, 0x8a, 0x2a, 0x8d, 0x18, 0x58, 0x4e, 0x57,
	0xfb, 0xa5, 0x39, 0xe5, 0x7c, 0xef, 0x74, 0xf7, 0x1c, 0xe1, 0x7e, 0x04, 0x26, 0x3e, 0x02, 0x1f,
	0x81, 0x8f, 0xc1, 0xd8, 0x11, 0x89, 0x05, 0x25, 0x03, 0x7c, 0x0c, 0xe4, 0xb3, 0x43, 0xa9, 0xe8,
	0x62, 0x3d, 0xbd, 0xdf, 0xef, 0xe7, 0xc1, 0x7e, 0x7c, 0x9f, 0x70, 0x06, 0x26, 0x9b, 0x4a, 0x65,
	0x52, 0x8d, 0x95, 0xd4, 0x54, 0xa5, 0xf3, 0x83, 0xd4, 0x4a, 0x27, 0x0b, 0x3f, 0xb4, 0x0e, 0x09,
	0xa3, 0xed, 0x6b, 0x67, 0xd8, 0x3a, 0xc3, 0xf9, 0x41, 0xef, 0x91, 0x2c, 0x94, 0xc1, 0x34, 0x3c,
	0x1b, 0xb3, 0xb7, 0x75, 0x81, 0x17, 0x18, 0xc6, 0xb4, 0x9e, 0x9a, 0xed, 0xfe, 0x8f, 0x35, 0xde,
	0x3d, 0x0d, 0x2f, 0x8c, 0x9e, 0xf0, 0x87, 0x99, 0x03, 0x49, 0x0a, 0x8d, 0x28, 0x30, 0x87, 0x98,
	0xf5, 0xd9, 0xe0, 0xfe, 0xe8, 0xc1, 0x6a, 0x79, 0x82, 0x39, 0x44, 0xcf, 0xf9, 0x76, 0x2e, 0x95,
	0xae, 0x84, 0x43, 0xad, 0x4b, 0x2b, 0x48, 0x15, 0x70, 0x89, 0x06, 0xe2, 0x3b, 0x41, 0xde, 0x0c,
	0x70, 0x14, 0xd8, 0xb8, 0x45, 0xd1, 0x11, 0xdf, 0x21, 0xf0, 0x64, 0x80, 0x82, 0xae, 0x31, 0x9b,
	0x89, 0x29, 0x96, 0xce, 0xc7, 0x6b, 0x7d, 0x36, 0x58, 0x1f, 0x6d, 0xb5, 0x74, 0xdc, 0xc2, 0x37,
	0x35, 0xab, 0xab, 0x42, 0x2a, 0x73, 0x4b, 0xb5, 0xde, 0x54, 0x2d, 0xbd, 0x59, 0xbd, 0xe0, 0xbb,
	0x13, 0x00, 0xe1, 0xad, 0x56, 0x24, 0xe6, 0x52, 0xab, 0x5c, 0x12, 0x3a, 0x71, 0x6e, 0x7d, 0x7c,
	0xb7, 0xc9, 0x26, 0x00, 0x67, 0x35, 0x7d, 0xbf, 0x82, 0xc7, 0xd6, 0x47, 0xaf, 0xf8, 0xde, 0x75,
	0x16, 0x3e, 0xa9, 0xf0, 0x24, 0x67, 0xe0, 0x7c, 0x48, 0xbb, 0x21, 0xdd, 0x5d, 0xa5, 0xe3, 0x5a,
	0x38, 0x6b, 0xf8, 0x7f, 0x75, 0x01, 0x2e, 0x9b, 0x4a, 0x43, 0xc2, 0x22, 0xea, 0x50, 0xdf, 0xbb,
	0x59, 0x9f, 0xb4, 0xc2, 0x29, 0xa2, 0xae, 0xeb, 0x43, 0xbe, 0xe3, 0x41, 0x5d, 0x96, 0x0e, 0x04,
	0x5a, 0x12, 0xca, 0x88, 0x1c, 0x26, 0xb2, 0xd4, 0x14, 0x6f, 0xf4, 0xd9, 0x60, 0x63, 0xb4, 0xd9,
	0xd2, 0x77, 0x96, 0xde, 0x9a, 0xd7, 0x0d, 0x7a, 0xf9, 0xf4, 0xf7, 0x97, 0xc7, 0xec, 0xd3, 0xaf,
	0xaf, 0xcf, 0xf6, 0xfe, 0x39, 0x92, 0x8f, 0x7f, 0xcf, 0xa4, 0xf9, 0xa5, 0xc7, 0x47, 0xdf, 0x16,
	0x09, 0xbb, 0x5a, 0x24, 0xec, 0xe7, 0x22, 0x61, 0x9f, 0x97, 0x49, 0xe7, 0x6a, 0x99, 0x74, 0xbe,
	0x2f, 0x93, 0xce, 0x87, 0xde, 0xad, 0x19, 0x55, 0x16, 0xfc, 0x79, 0x37, 0x9c, 0xc6, 0xe1, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x50, 0x58, 0x1b, 0x80, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CreationMode != that1.CreationMode {
		return false
	}
	if this.DailyRollupTimezone != that1.DailyRollupTimezone {
		return false
	}
	if this.TestnetTimelockHours != that1.TestnetTimelockHours {
		return false
	}
	if this.MainnetTimelockHours != that1.MainnetTimelockHours {
		return false
	}
	if this.FeeSplitValidatorBps != that1.FeeSplitValidatorBps {
		return false
	}
	if this.FeeSplitTokenStakersBps != that1.FeeSplitTokenStakersBps {
		return false
	}
	if this.FeeSplitMerchantPoolBps != that1.FeeSplitMerchantPoolBps {
		return false
	}
	if this.SeizureOptInDefault != that1.SeizureOptInDefault {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SeizureOptInDefault {
		i--
		if m.SeizureOptInDefault {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.FeeSplitMerchantPoolBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeSplitMerchantPoolBps))
		i--
		dAtA[i] = 0x38
	}
	if m.FeeSplitTokenStakersBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeSplitTokenStakersBps))
		i--
		dAtA[i] = 0x30
	}
	if m.FeeSplitValidatorBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeSplitValidatorBps))
		i--
		dAtA[i] = 0x28
	}
	if m.MainnetTimelockHours != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MainnetTimelockHours))
		i--
		dAtA[i] = 0x20
	}
	if m.TestnetTimelockHours != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TestnetTimelockHours))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DailyRollupTimezone) > 0 {
		i -= len(m.DailyRollupTimezone)
		copy(dAtA[i:], m.DailyRollupTimezone)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DailyRollupTimezone)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreationMode) > 0 {
		i -= len(m.CreationMode)
		copy(dAtA[i:], m.CreationMode)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CreationMode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CreationMode)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DailyRollupTimezone)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.TestnetTimelockHours != 0 {
		n += 1 + sovParams(uint64(m.TestnetTimelockHours))
	}
	if m.MainnetTimelockHours != 0 {
		n += 1 + sovParams(uint64(m.MainnetTimelockHours))
	}
	if m.FeeSplitValidatorBps != 0 {
		n += 1 + sovParams(uint64(m.FeeSplitValidatorBps))
	}
	if m.FeeSplitTokenStakersBps != 0 {
		n += 1 + sovParams(uint64(m.FeeSplitTokenStakersBps))
	}
	if m.FeeSplitMerchantPoolBps != 0 {
		n += 1 + sovParams(uint64(m.FeeSplitMerchantPoolBps))
	}
	if m.SeizureOptInDefault {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationMode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreationMode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyRollupTimezone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DailyRollupTimezone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestnetTimelockHours", wireType)
			}
			m.TestnetTimelockHours = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TestnetTimelockHours |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainnetTimelockHours", wireType)
			}
			m.MainnetTimelockHours = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MainnetTimelockHours |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSplitValidatorBps", wireType)
			}
			m.FeeSplitValidatorBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeSplitValidatorBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSplitTokenStakersBps", wireType)
			}
			m.FeeSplitTokenStakersBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeSplitTokenStakersBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSplitMerchantPoolBps", wireType)
			}
			m.FeeSplitMerchantPoolBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeSplitMerchantPoolBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeizureOptInDefault", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeizureOptInDefault = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
