// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/loyalty/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetCreatorallowlistRequest defines the QueryGetCreatorallowlistRequest message.
type QueryGetCreatorallowlistRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetCreatorallowlistRequest) Reset()         { *m = QueryGetCreatorallowlistRequest{} }
func (m *QueryGetCreatorallowlistRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatorallowlistRequest) ProtoMessage()    {}
func (*QueryGetCreatorallowlistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{2}
}
func (m *QueryGetCreatorallowlistRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatorallowlistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatorallowlistRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatorallowlistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatorallowlistRequest.Merge(m, src)
}
func (m *QueryGetCreatorallowlistRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatorallowlistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatorallowlistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatorallowlistRequest proto.InternalMessageInfo

func (m *QueryGetCreatorallowlistRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryGetCreatorallowlistResponse defines the QueryGetCreatorallowlistResponse message.
type QueryGetCreatorallowlistResponse struct {
	Creatorallowlist Creatorallowlist `protobuf:"bytes,1,opt,name=creatorallowlist,proto3" json:"creatorallowlist"`
}

func (m *QueryGetCreatorallowlistResponse) Reset()         { *m = QueryGetCreatorallowlistResponse{} }
func (m *QueryGetCreatorallowlistResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatorallowlistResponse) ProtoMessage()    {}
func (*QueryGetCreatorallowlistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{3}
}
func (m *QueryGetCreatorallowlistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatorallowlistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatorallowlistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatorallowlistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatorallowlistResponse.Merge(m, src)
}
func (m *QueryGetCreatorallowlistResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatorallowlistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatorallowlistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatorallowlistResponse proto.InternalMessageInfo

func (m *QueryGetCreatorallowlistResponse) GetCreatorallowlist() Creatorallowlist {
	if m != nil {
		return m.Creatorallowlist
	}
	return Creatorallowlist{}
}

// QueryAllCreatorallowlistRequest defines the QueryAllCreatorallowlistRequest message.
type QueryAllCreatorallowlistRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatorallowlistRequest) Reset()         { *m = QueryAllCreatorallowlistRequest{} }
func (m *QueryAllCreatorallowlistRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatorallowlistRequest) ProtoMessage()    {}
func (*QueryAllCreatorallowlistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{4}
}
func (m *QueryAllCreatorallowlistRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatorallowlistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatorallowlistRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatorallowlistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatorallowlistRequest.Merge(m, src)
}
func (m *QueryAllCreatorallowlistRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatorallowlistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatorallowlistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatorallowlistRequest proto.InternalMessageInfo

func (m *QueryAllCreatorallowlistRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllCreatorallowlistResponse defines the QueryAllCreatorallowlistResponse message.
type QueryAllCreatorallowlistResponse struct {
	Creatorallowlist []Creatorallowlist  `protobuf:"bytes,1,rep,name=creatorallowlist,proto3" json:"creatorallowlist"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatorallowlistResponse) Reset()         { *m = QueryAllCreatorallowlistResponse{} }
func (m *QueryAllCreatorallowlistResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatorallowlistResponse) ProtoMessage()    {}
func (*QueryAllCreatorallowlistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{5}
}
func (m *QueryAllCreatorallowlistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatorallowlistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatorallowlistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatorallowlistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatorallowlistResponse.Merge(m, src)
}
func (m *QueryAllCreatorallowlistResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatorallowlistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatorallowlistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatorallowlistResponse proto.InternalMessageInfo

func (m *QueryAllCreatorallowlistResponse) GetCreatorallowlist() []Creatorallowlist {
	if m != nil {
		return m.Creatorallowlist
	}
	return nil
}

func (m *QueryAllCreatorallowlistResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetVerifiedtokenRequest defines the QueryGetVerifiedtokenRequest message.
type QueryGetVerifiedtokenRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryGetVerifiedtokenRequest) Reset()         { *m = QueryGetVerifiedtokenRequest{} }
func (m *QueryGetVerifiedtokenRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerifiedtokenRequest) ProtoMessage()    {}
func (*QueryGetVerifiedtokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{6}
}
func (m *QueryGetVerifiedtokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerifiedtokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerifiedtokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerifiedtokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerifiedtokenRequest.Merge(m, src)
}
func (m *QueryGetVerifiedtokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerifiedtokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerifiedtokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerifiedtokenRequest proto.InternalMessageInfo

func (m *QueryGetVerifiedtokenRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryGetVerifiedtokenResponse defines the QueryGetVerifiedtokenResponse message.
type QueryGetVerifiedtokenResponse struct {
	Verifiedtoken Verifiedtoken `protobuf:"bytes,1,opt,name=verifiedtoken,proto3" json:"verifiedtoken"`
}

func (m *QueryGetVerifiedtokenResponse) Reset()         { *m = QueryGetVerifiedtokenResponse{} }
func (m *QueryGetVerifiedtokenResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerifiedtokenResponse) ProtoMessage()    {}
func (*QueryGetVerifiedtokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{7}
}
func (m *QueryGetVerifiedtokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerifiedtokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerifiedtokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerifiedtokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerifiedtokenResponse.Merge(m, src)
}
func (m *QueryGetVerifiedtokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerifiedtokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerifiedtokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerifiedtokenResponse proto.InternalMessageInfo

func (m *QueryGetVerifiedtokenResponse) GetVerifiedtoken() Verifiedtoken {
	if m != nil {
		return m.Verifiedtoken
	}
	return Verifiedtoken{}
}

// QueryAllVerifiedtokenRequest defines the QueryAllVerifiedtokenRequest message.
type QueryAllVerifiedtokenRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVerifiedtokenRequest) Reset()         { *m = QueryAllVerifiedtokenRequest{} }
func (m *QueryAllVerifiedtokenRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVerifiedtokenRequest) ProtoMessage()    {}
func (*QueryAllVerifiedtokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{8}
}
func (m *QueryAllVerifiedtokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVerifiedtokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVerifiedtokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVerifiedtokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVerifiedtokenRequest.Merge(m, src)
}
func (m *QueryAllVerifiedtokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVerifiedtokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVerifiedtokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVerifiedtokenRequest proto.InternalMessageInfo

func (m *QueryAllVerifiedtokenRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllVerifiedtokenResponse defines the QueryAllVerifiedtokenResponse message.
type QueryAllVerifiedtokenResponse struct {
	Verifiedtoken []Verifiedtoken     `protobuf:"bytes,1,rep,name=verifiedtoken,proto3" json:"verifiedtoken"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVerifiedtokenResponse) Reset()         { *m = QueryAllVerifiedtokenResponse{} }
func (m *QueryAllVerifiedtokenResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVerifiedtokenResponse) ProtoMessage()    {}
func (*QueryAllVerifiedtokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{9}
}
func (m *QueryAllVerifiedtokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVerifiedtokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVerifiedtokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVerifiedtokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVerifiedtokenResponse.Merge(m, src)
}
func (m *QueryAllVerifiedtokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVerifiedtokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVerifiedtokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVerifiedtokenResponse proto.InternalMessageInfo

func (m *QueryAllVerifiedtokenResponse) GetVerifiedtoken() []Verifiedtoken {
	if m != nil {
		return m.Verifiedtoken
	}
	return nil
}

func (m *QueryAllVerifiedtokenResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetRewardaccrualRequest defines the QueryGetRewardaccrualRequest message.
type QueryGetRewardaccrualRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *QueryGetRewardaccrualRequest) Reset()         { *m = QueryGetRewardaccrualRequest{} }
func (m *QueryGetRewardaccrualRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRewardaccrualRequest) ProtoMessage()    {}
func (*QueryGetRewardaccrualRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{10}
}
func (m *QueryGetRewardaccrualRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRewardaccrualRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRewardaccrualRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRewardaccrualRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRewardaccrualRequest.Merge(m, src)
}
func (m *QueryGetRewardaccrualRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRewardaccrualRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRewardaccrualRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRewardaccrualRequest proto.InternalMessageInfo

func (m *QueryGetRewardaccrualRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// QueryGetRewardaccrualResponse defines the QueryGetRewardaccrualResponse message.
type QueryGetRewardaccrualResponse struct {
	Rewardaccrual Rewardaccrual `protobuf:"bytes,1,opt,name=rewardaccrual,proto3" json:"rewardaccrual"`
}

func (m *QueryGetRewardaccrualResponse) Reset()         { *m = QueryGetRewardaccrualResponse{} }
func (m *QueryGetRewardaccrualResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRewardaccrualResponse) ProtoMessage()    {}
func (*QueryGetRewardaccrualResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{11}
}
func (m *QueryGetRewardaccrualResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRewardaccrualResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRewardaccrualResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRewardaccrualResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRewardaccrualResponse.Merge(m, src)
}
func (m *QueryGetRewardaccrualResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRewardaccrualResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRewardaccrualResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRewardaccrualResponse proto.InternalMessageInfo

func (m *QueryGetRewardaccrualResponse) GetRewardaccrual() Rewardaccrual {
	if m != nil {
		return m.Rewardaccrual
	}
	return Rewardaccrual{}
}

// QueryAllRewardaccrualRequest defines the QueryAllRewardaccrualRequest message.
type QueryAllRewardaccrualRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRewardaccrualRequest) Reset()         { *m = QueryAllRewardaccrualRequest{} }
func (m *QueryAllRewardaccrualRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRewardaccrualRequest) ProtoMessage()    {}
func (*QueryAllRewardaccrualRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{12}
}
func (m *QueryAllRewardaccrualRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRewardaccrualRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRewardaccrualRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRewardaccrualRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRewardaccrualRequest.Merge(m, src)
}
func (m *QueryAllRewardaccrualRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRewardaccrualRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRewardaccrualRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRewardaccrualRequest proto.InternalMessageInfo

func (m *QueryAllRewardaccrualRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllRewardaccrualResponse defines the QueryAllRewardaccrualResponse message.
type QueryAllRewardaccrualResponse struct {
	Rewardaccrual []Rewardaccrual     `protobuf:"bytes,1,rep,name=rewardaccrual,proto3" json:"rewardaccrual"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRewardaccrualResponse) Reset()         { *m = QueryAllRewardaccrualResponse{} }
func (m *QueryAllRewardaccrualResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRewardaccrualResponse) ProtoMessage()    {}
func (*QueryAllRewardaccrualResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ce6a4b5ffcb3a1, []int{13}
}
func (m *QueryAllRewardaccrualResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRewardaccrualResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRewardaccrualResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRewardaccrualResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRewardaccrualResponse.Merge(m, src)
}
func (m *QueryAllRewardaccrualResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRewardaccrualResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRewardaccrualResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRewardaccrualResponse proto.InternalMessageInfo

func (m *QueryAllRewardaccrualResponse) GetRewardaccrual() []Rewardaccrual {
	if m != nil {
		return m.Rewardaccrual
	}
	return nil
}

func (m *QueryAllRewardaccrualResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "tokenchain.loyalty.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "tokenchain.loyalty.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetCreatorallowlistRequest)(nil), "tokenchain.loyalty.v1.QueryGetCreatorallowlistRequest")
	proto.RegisterType((*QueryGetCreatorallowlistResponse)(nil), "tokenchain.loyalty.v1.QueryGetCreatorallowlistResponse")
	proto.RegisterType((*QueryAllCreatorallowlistRequest)(nil), "tokenchain.loyalty.v1.QueryAllCreatorallowlistRequest")
	proto.RegisterType((*QueryAllCreatorallowlistResponse)(nil), "tokenchain.loyalty.v1.QueryAllCreatorallowlistResponse")
	proto.RegisterType((*QueryGetVerifiedtokenRequest)(nil), "tokenchain.loyalty.v1.QueryGetVerifiedtokenRequest")
	proto.RegisterType((*QueryGetVerifiedtokenResponse)(nil), "tokenchain.loyalty.v1.QueryGetVerifiedtokenResponse")
	proto.RegisterType((*QueryAllVerifiedtokenRequest)(nil), "tokenchain.loyalty.v1.QueryAllVerifiedtokenRequest")
	proto.RegisterType((*QueryAllVerifiedtokenResponse)(nil), "tokenchain.loyalty.v1.QueryAllVerifiedtokenResponse")
	proto.RegisterType((*QueryGetRewardaccrualRequest)(nil), "tokenchain.loyalty.v1.QueryGetRewardaccrualRequest")
	proto.RegisterType((*QueryGetRewardaccrualResponse)(nil), "tokenchain.loyalty.v1.QueryGetRewardaccrualResponse")
	proto.RegisterType((*QueryAllRewardaccrualRequest)(nil), "tokenchain.loyalty.v1.QueryAllRewardaccrualRequest")
	proto.RegisterType((*QueryAllRewardaccrualResponse)(nil), "tokenchain.loyalty.v1.QueryAllRewardaccrualResponse")
}

func init() { proto.RegisterFile("tokenchain/loyalty/v1/query.proto", fileDescriptor_d3ce6a4b5ffcb3a1) }

var fileDescriptor_d3ce6a4b5ffcb3a1 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x4f, 0x13, 0x4f,
	0x14, 0xef, 0xd0, 0x2f, 0x7c, 0xc3, 0x18, 0x13, 0x18, 0x6a, 0x42, 0x1a, 0x28, 0x38, 0x41, 0x90,
	0xa6, 0xd9, 0xb1, 0xd0, 0x68, 0x8c, 0x17, 0xc1, 0x44, 0x2e, 0x1e, 0xb0, 0x07, 0x8d, 0xde, 0x86,
	0x76, 0xa8, 0x1b, 0xb6, 0x3b, 0x65, 0x77, 0x29, 0x36, 0x84, 0x8b, 0x07, 0xcf, 0x26, 0xfe, 0x13,
	0x1e, 0x3c, 0x68, 0xbc, 0x18, 0x6f, 0x5e, 0x0c, 0x47, 0x12, 0x0f, 0x7a, 0x32, 0x06, 0x4c, 0xfc,
	0x37, 0x4c, 0x67, 0x5e, 0x6d, 0xb7, 0xdd, 0x5f, 0x0d, 0xf5, 0xd2, 0xcc, 0xee, 0xbe, 0x1f, 0x9f,
	0xcf, 0xe7, 0xbd, 0xbe, 0x37, 0xf8, 0xaa, 0x27, 0xf7, 0x84, 0x5d, 0x79, 0xc6, 0x4d, 0x9b, 0x59,
	0xb2, 0xc5, 0x2d, 0xaf, 0xc5, 0x9a, 0x45, 0xb6, 0x7f, 0x20, 0x9c, 0x96, 0xd1, 0x70, 0xa4, 0x27,
	0xc9, 0x95, 0xae, 0x89, 0x01, 0x26, 0x46, 0xb3, 0x98, 0x9d, 0xe6, 0x75, 0xd3, 0x96, 0x4c, 0xfd,
	0x6a, 0xcb, 0x6c, 0xbe, 0x22, 0xdd, 0xba, 0x74, 0xd9, 0x0e, 0x77, 0x85, 0x0e, 0xc1, 0x9a, 0xc5,
	0x1d, 0xe1, 0xf1, 0x22, 0x6b, 0xf0, 0x9a, 0x69, 0x73, 0xcf, 0x94, 0x36, 0xd8, 0x66, 0x6a, 0xb2,
	0x26, 0xd5, 0x91, 0xb5, 0x4f, 0xf0, 0x76, 0xae, 0x26, 0x65, 0xcd, 0x12, 0x8c, 0x37, 0x4c, 0xc6,
	0x6d, 0x5b, 0x7a, 0xca, 0xc5, 0x85, 0xaf, 0x85, 0x60, 0xb0, 0x15, 0x47, 0x70, 0x4f, 0x3a, 0xdc,
	0xb2, 0xe4, 0xa1, 0x65, 0xba, 0x1e, 0x58, 0xd3, 0x60, 0xeb, 0x06, 0x77, 0x78, 0xbd, 0x13, 0x71,
	0x35, 0xd8, 0xc6, 0x11, 0x87, 0xdc, 0xa9, 0xf2, 0x4a, 0xc5, 0x39, 0xe0, 0x56, 0xb4, 0x69, 0x53,
	0x38, 0xe6, 0xae, 0x29, 0xaa, 0xea, 0xab, 0x36, 0xa5, 0x19, 0x4c, 0x1e, 0xb6, 0xd9, 0x6f, 0xab,
	0x54, 0x65, 0xb1, 0x7f, 0x20, 0x5c, 0x8f, 0x3e, 0xc6, 0x33, 0xbe, 0xb7, 0x6e, 0x43, 0xda, 0xae,
	0x20, 0x77, 0xf1, 0x84, 0x86, 0x34, 0x8b, 0x16, 0xd1, 0xf5, 0x4b, 0x6b, 0xf3, 0x46, 0xa0, 0xde,
	0x86, 0x76, 0xdb, 0x9c, 0x3c, 0xf9, 0xb1, 0x90, 0x7a, 0xf3, 0xfb, 0x5d, 0x1e, 0x95, 0xc1, 0x8f,
	0xde, 0xc1, 0x0b, 0x2a, 0xf0, 0x96, 0xf0, 0xee, 0xf5, 0x49, 0x01, 0xb9, 0xc9, 0x2c, 0xfe, 0x9f,
	0x57, 0xab, 0x8e, 0x70, 0x75, 0x96, 0xc9, 0x72, 0xe7, 0x91, 0x1e, 0xe3, 0xc5, 0x70, 0x67, 0x80,
	0xf8, 0x04, 0x4f, 0xf5, 0x6b, 0x0c, 0x60, 0x57, 0x42, 0xc0, 0xf6, 0x87, 0xda, 0xfc, 0xaf, 0x0d,
	0xbb, 0x3c, 0x10, 0x86, 0x9a, 0x80, 0x7d, 0xc3, 0xb2, 0xc2, 0xb0, 0xdf, 0xc7, 0xb8, 0xdb, 0x3d,
	0x90, 0x77, 0xd9, 0xd0, 0xad, 0x66, 0xb4, 0x5b, 0xcd, 0xd0, 0xdd, 0x0a, 0xad, 0x66, 0x6c, 0xf3,
	0x9a, 0x00, 0xdf, 0x72, 0x8f, 0x27, 0xfd, 0x82, 0x80, 0x6a, 0x60, 0xae, 0x48, 0xaa, 0xe9, 0x11,
	0x50, 0x25, 0x5b, 0x3e, 0x1e, 0x63, 0xa0, 0x5f, 0x1c, 0x0f, 0x8d, 0xcb, 0x47, 0xa4, 0x84, 0xe7,
	0x3a, 0x25, 0x7b, 0xd4, 0xdb, 0x7d, 0x1d, 0xc1, 0x32, 0x78, 0xbc, 0x2a, 0x6c, 0x59, 0x87, 0x52,
	0xeb, 0x07, 0xba, 0x8f, 0xe7, 0x43, 0xbc, 0x80, 0xfa, 0x36, 0xbe, 0xec, 0x6b, 0x66, 0x90, 0x7a,
	0x29, 0x84, 0xb7, 0x2f, 0x08, 0x90, 0xf6, 0x07, 0xa0, 0xbb, 0x00, 0x74, 0xc3, 0xb2, 0x02, 0x81,
	0x8e, 0xaa, 0xb2, 0x9f, 0x10, 0x70, 0x1b, 0x4c, 0x14, 0xce, 0x2d, 0x7d, 0x21, 0x6e, 0xa3, 0xab,
	0xe6, 0x8d, 0x6e, 0x35, 0xcb, 0xbd, 0x63, 0xa7, 0x23, 0xd2, 0x14, 0x4e, 0xef, 0x89, 0x16, 0xd4,
	0xb2, 0x7d, 0xec, 0xad, 0x64, 0x9f, 0x47, 0x97, 0xad, 0x6f, 0x82, 0xc5, 0x54, 0xd2, 0x17, 0xa4,
	0xc3, 0xd6, 0x17, 0xa0, 0xb7, 0x92, 0x81, 0x20, 0xff, 0x45, 0x25, 0x13, 0x73, 0x4b, 0x5f, 0x88,
	0xdb, 0xc8, 0x2a, 0xb9, 0xf6, 0x6d, 0x12, 0x8f, 0x2b, 0xf0, 0xe4, 0x25, 0xc2, 0x13, 0x7a, 0x5e,
	0x93, 0xd5, 0x10, 0x60, 0x83, 0x0b, 0x22, 0x9b, 0x4f, 0x62, 0xaa, 0xf3, 0xd2, 0x6b, 0x2f, 0xbe,
	0xfe, 0x7a, 0x3d, 0xb6, 0x40, 0xe6, 0x59, 0xd4, 0x96, 0x23, 0x9f, 0x11, 0x9e, 0x09, 0x98, 0xec,
	0xe4, 0x66, 0x54, 0xaa, 0xf0, 0x3d, 0x92, 0xbd, 0x35, 0xb4, 0x1f, 0xe0, 0xbd, 0xad, 0xf0, 0xae,
	0x93, 0x22, 0x4b, 0xb6, 0xc3, 0xd9, 0x11, 0x2c, 0xa8, 0x63, 0xf2, 0x11, 0xe1, 0xcc, 0x03, 0xd3,
	0x1d, 0x92, 0x44, 0xf8, 0x42, 0x89, 0x26, 0x11, 0xb1, 0x1c, 0x28, 0x53, 0x24, 0x56, 0xc9, 0x4a,
	0x42, 0x12, 0xe4, 0x03, 0xc2, 0x53, 0xfd, 0xf3, 0x96, 0xac, 0xc7, 0x68, 0x18, 0x34, 0x2a, 0xb3,
	0xa5, 0xe1, 0x9c, 0x00, 0x70, 0x49, 0x01, 0x36, 0x48, 0x81, 0x25, 0xb8, 0xbc, 0xb0, 0x23, 0xb5,
	0x28, 0x8e, 0xc9, 0x5b, 0x84, 0xa7, 0xdb, 0x82, 0x0f, 0x01, 0x3b, 0x64, 0xc2, 0x47, 0xc3, 0x0e,
	0x9b, 0xd6, 0xb4, 0xa0, 0x60, 0x2f, 0x93, 0xa5, 0x24, 0xb0, 0xc9, 0x7b, 0x2d, 0xb2, 0xef, 0x9f,
	0x1e, 0x2b, 0x72, 0xd0, 0x14, 0x8b, 0x15, 0x39, 0x70, 0x22, 0xd1, 0x35, 0x85, 0xb6, 0x40, 0xf2,
	0x2c, 0xc1, 0x65, 0x92, 0x1d, 0xed, 0x89, 0x56, 0x57, 0xe2, 0x21, 0x40, 0x87, 0x8c, 0xde, 0x58,
	0x89, 0x83, 0x41, 0xc7, 0x49, 0xec, 0x03, 0xbd, 0x59, 0x3a, 0x39, 0xcb, 0xa1, 0xd3, 0xb3, 0x1c,
	0xfa, 0x79, 0x96, 0x43, 0xaf, 0xce, 0x73, 0xa9, 0xd3, 0xf3, 0x5c, 0xea, 0xfb, 0x79, 0x2e, 0xf5,
	0x34, 0xdb, 0xe3, 0xfe, 0xfc, 0x6f, 0x00, 0xaf, 0xd5, 0x10, 0xee, 0xce, 0x84, 0xba, 0x0d, 0xaf,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xad, 0x8d, 0xd3, 0xa7, 0x64, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListCreatorallowlist Queries a list of Creatorallowlist items.
	GetCreatorallowlist(ctx context.Context, in *QueryGetCreatorallowlistRequest, opts ...grpc.CallOption) (*QueryGetCreatorallowlistResponse, error)
	// ListCreatorallowlist defines the ListCreatorallowlist RPC.
	ListCreatorallowlist(ctx context.Context, in *QueryAllCreatorallowlistRequest, opts ...grpc.CallOption) (*QueryAllCreatorallowlistResponse, error)
	// ListVerifiedtoken Queries a list of Verifiedtoken items.
	GetVerifiedtoken(ctx context.Context, in *QueryGetVerifiedtokenRequest, opts ...grpc.CallOption) (*QueryGetVerifiedtokenResponse, error)
	// ListVerifiedtoken defines the ListVerifiedtoken RPC.
	ListVerifiedtoken(ctx context.Context, in *QueryAllVerifiedtokenRequest, opts ...grpc.CallOption) (*QueryAllVerifiedtokenResponse, error)
	// ListRewardaccrual Queries a list of Rewardaccrual items.
	GetRewardaccrual(ctx context.Context, in *QueryGetRewardaccrualRequest, opts ...grpc.CallOption) (*QueryGetRewardaccrualResponse, error)
	// ListRewardaccrual defines the ListRewardaccrual RPC.
	ListRewardaccrual(ctx context.Context, in *QueryAllRewardaccrualRequest, opts ...grpc.CallOption) (*QueryAllRewardaccrualResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCreatorallowlist(ctx context.Context, in *QueryGetCreatorallowlistRequest, opts ...grpc.CallOption) (*QueryGetCreatorallowlistResponse, error) {
	out := new(QueryGetCreatorallowlistResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/GetCreatorallowlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListCreatorallowlist(ctx context.Context, in *QueryAllCreatorallowlistRequest, opts ...grpc.CallOption) (*QueryAllCreatorallowlistResponse, error) {
	out := new(QueryAllCreatorallowlistResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/ListCreatorallowlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVerifiedtoken(ctx context.Context, in *QueryGetVerifiedtokenRequest, opts ...grpc.CallOption) (*QueryGetVerifiedtokenResponse, error) {
	out := new(QueryGetVerifiedtokenResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/GetVerifiedtoken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListVerifiedtoken(ctx context.Context, in *QueryAllVerifiedtokenRequest, opts ...grpc.CallOption) (*QueryAllVerifiedtokenResponse, error) {
	out := new(QueryAllVerifiedtokenResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/ListVerifiedtoken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRewardaccrual(ctx context.Context, in *QueryGetRewardaccrualRequest, opts ...grpc.CallOption) (*QueryGetRewardaccrualResponse, error) {
	out := new(QueryGetRewardaccrualResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/GetRewardaccrual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListRewardaccrual(ctx context.Context, in *QueryAllRewardaccrualRequest, opts ...grpc.CallOption) (*QueryAllRewardaccrualResponse, error) {
	out := new(QueryAllRewardaccrualResponse)
	err := c.cc.Invoke(ctx, "/tokenchain.loyalty.v1.Query/ListRewardaccrual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListCreatorallowlist Queries a list of Creatorallowlist items.
	GetCreatorallowlist(context.Context, *QueryGetCreatorallowlistRequest) (*QueryGetCreatorallowlistResponse, error)
	// ListCreatorallowlist defines the ListCreatorallowlist RPC.
	ListCreatorallowlist(context.Context, *QueryAllCreatorallowlistRequest) (*QueryAllCreatorallowlistResponse, error)
	// ListVerifiedtoken Queries a list of Verifiedtoken items.
	GetVerifiedtoken(context.Context, *QueryGetVerifiedtokenRequest) (*QueryGetVerifiedtokenResponse, error)
	// ListVerifiedtoken defines the ListVerifiedtoken RPC.
	ListVerifiedtoken(context.Context, *QueryAllVerifiedtokenRequest) (*QueryAllVerifiedtokenResponse, error)
	// ListRewardaccrual Queries a list of Rewardaccrual items.
	GetRewardaccrual(context.Context, *QueryGetRewardaccrualRequest) (*QueryGetRewardaccrualResponse, error)
	// ListRewardaccrual defines the ListRewardaccrual RPC.
	ListRewardaccrual(context.Context, *QueryAllRewardaccrualRequest) (*QueryAllRewardaccrualResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetCreatorallowlist(ctx context.Context, req *QueryGetCreatorallowlistRequest) (*QueryGetCreatorallowlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreatorallowlist not implemented")
}
func (*UnimplementedQueryServer) ListCreatorallowlist(ctx context.Context, req *QueryAllCreatorallowlistRequest) (*QueryAllCreatorallowlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCreatorallowlist not implemented")
}
func (*UnimplementedQueryServer) GetVerifiedtoken(ctx context.Context, req *QueryGetVerifiedtokenRequest) (*QueryGetVerifiedtokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifiedtoken not implemented")
}
func (*UnimplementedQueryServer) ListVerifiedtoken(ctx context.Context, req *QueryAllVerifiedtokenRequest) (*QueryAllVerifiedtokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVerifiedtoken not implemented")
}
func (*UnimplementedQueryServer) GetRewardaccrual(ctx context.Context, req *QueryGetRewardaccrualRequest) (*QueryGetRewardaccrualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardaccrual not implemented")
}
func (*UnimplementedQueryServer) ListRewardaccrual(ctx context.Context, req *QueryAllRewardaccrualRequest) (*QueryAllRewardaccrualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRewardaccrual not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCreatorallowlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatorallowlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCreatorallowlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/GetCreatorallowlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCreatorallowlist(ctx, req.(*QueryGetCreatorallowlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListCreatorallowlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCreatorallowlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListCreatorallowlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/ListCreatorallowlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListCreatorallowlist(ctx, req.(*QueryAllCreatorallowlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVerifiedtoken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVerifiedtokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVerifiedtoken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/GetVerifiedtoken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVerifiedtoken(ctx, req.(*QueryGetVerifiedtokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListVerifiedtoken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVerifiedtokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListVerifiedtoken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/ListVerifiedtoken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListVerifiedtoken(ctx, req.(*QueryAllVerifiedtokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRewardaccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRewardaccrualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRewardaccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/GetRewardaccrual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRewardaccrual(ctx, req.(*QueryGetRewardaccrualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListRewardaccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRewardaccrualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListRewardaccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenchain.loyalty.v1.Query/ListRewardaccrual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListRewardaccrual(ctx, req.(*QueryAllRewardaccrualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenchain.loyalty.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetCreatorallowlist",
			Handler:    _Query_GetCreatorallowlist_Handler,
		},
		{
			MethodName: "ListCreatorallowlist",
			Handler:    _Query_ListCreatorallowlist_Handler,
		},
		{
			MethodName: "GetVerifiedtoken",
			Handler:    _Query_GetVerifiedtoken_Handler,
		},
		{
			MethodName: "ListVerifiedtoken",
			Handler:    _Query_ListVerifiedtoken_Handler,
		},
		{
			MethodName: "GetRewardaccrual",
			Handler:    _Query_GetRewardaccrual_Handler,
		},
		{
			MethodName: "ListRewardaccrual",
			Handler:    _Query_ListRewardaccrual_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenchain/loyalty/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatorallowlistRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatorallowlistRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatorallowlistRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatorallowlistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatorallowlistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatorallowlistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Creatorallowlist.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatorallowlistRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatorallowlistRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatorallowlistRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatorallowlistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatorallowlistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatorallowlistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creatorallowlist) > 0 {
		for iNdEx := len(m.Creatorallowlist) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Creatorallowlist[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVerifiedtokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerifiedtokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerifiedtokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVerifiedtokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerifiedtokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerifiedtokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Verifiedtoken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVerifiedtokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVerifiedtokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVerifiedtokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVerifiedtokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVerifiedtokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVerifiedtokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Verifiedtoken) > 0 {
		for iNdEx := len(m.Verifiedtoken) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Verifiedtoken[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRewardaccrualRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRewardaccrualRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRewardaccrualRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRewardaccrualResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRewardaccrualResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRewardaccrualResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Rewardaccrual.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRewardaccrualRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRewardaccrualRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRewardaccrualRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRewardaccrualResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRewardaccrualResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRewardaccrualResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Rewardaccrual) > 0 {
		for iNdEx := len(m.Rewardaccrual) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewardaccrual[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCreatorallowlistRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCreatorallowlistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Creatorallowlist.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCreatorallowlistRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatorallowlistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Creatorallowlist) > 0 {
		for _, e := range m.Creatorallowlist {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVerifiedtokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVerifiedtokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Verifiedtoken.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVerifiedtokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVerifiedtokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Verifiedtoken) > 0 {
		for _, e := range m.Verifiedtoken {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRewardaccrualRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRewardaccrualResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Rewardaccrual.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRewardaccrualRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRewardaccrualResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rewardaccrual) > 0 {
		for _, e := range m.Rewardaccrual {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatorallowlistRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatorallowlistRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatorallowlistRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatorallowlistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatorallowlistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatorallowlistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creatorallowlist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Creatorallowlist.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatorallowlistRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatorallowlistRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatorallowlistRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatorallowlistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatorallowlistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatorallowlistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creatorallowlist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creatorallowlist = append(m.Creatorallowlist, Creatorallowlist{})
			if err := m.Creatorallowlist[len(m.Creatorallowlist)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerifiedtokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerifiedtokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerifiedtokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerifiedtokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerifiedtokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerifiedtokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verifiedtoken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Verifiedtoken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVerifiedtokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVerifiedtokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVerifiedtokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVerifiedtokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVerifiedtokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVerifiedtokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verifiedtoken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Verifiedtoken = append(m.Verifiedtoken, Verifiedtoken{})
			if err := m.Verifiedtoken[len(m.Verifiedtoken)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRewardaccrualRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRewardaccrualRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRewardaccrualRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRewardaccrualResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRewardaccrualResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRewardaccrualResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewardaccrual", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rewardaccrual.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRewardaccrualRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRewardaccrualRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRewardaccrualRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRewardaccrualResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRewardaccrualResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRewardaccrualResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewardaccrual", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewardaccrual = append(m.Rewardaccrual, Rewardaccrual{})
			if err := m.Rewardaccrual[len(m.Rewardaccrual)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
