// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/loyalty/v1/recoveryoperation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Recoveryoperation defines the Recoveryoperation message.
type Recoveryoperation struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Denom        string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	FromAddress  string `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress    string `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount       uint64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestedBy  string `protobuf:"bytes,6,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	ExecuteAfter uint64 `protobuf:"varint,7,opt,name=execute_after,json=executeAfter,proto3" json:"execute_after,omitempty"`
	CreatedAt    uint64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status       string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ExecutedAt   uint64 `protobuf:"varint,10,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	CancelledAt  uint64 `protobuf:"varint,11,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancelReason string `protobuf:"bytes,12,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
}

func (m *Recoveryoperation) Reset()         { *m = Recoveryoperation{} }
func (m *Recoveryoperation) String() string { return proto.CompactTextString(m) }
func (*Recoveryoperation) ProtoMessage()    {}
func (*Recoveryoperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cf1416d21b7f9ab, []int{0}
}
func (m *Recoveryoperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Recoveryoperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Recoveryoperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Recoveryoperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recoveryoperation.Merge(m, src)
}
func (m *Recoveryoperation) XXX_Size() int {
	return m.Size()
}
func (m *Recoveryoperation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recoveryoperation.DiscardUnknown(m)
}

var xxx_messageInfo_Recoveryoperation proto.InternalMessageInfo

func (m *Recoveryoperation) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recoveryoperation) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Recoveryoperation) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *Recoveryoperation) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *Recoveryoperation) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Recoveryoperation) GetRequestedBy() string {
	if m != nil {
		return m.RequestedBy
	}
	return ""
}

func (m *Recoveryoperation) GetExecuteAfter() uint64 {
	if m != nil {
		return m.ExecuteAfter
	}
	return 0
}

func (m *Recoveryoperation) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Recoveryoperation) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Recoveryoperation) GetExecutedAt() uint64 {
	if m != nil {
		return m.ExecutedAt
	}
	return 0
}

func (m *Recoveryoperation) GetCancelledAt() uint64 {
	if m != nil {
		return m.CancelledAt
	}
	return 0
}

func (m *Recoveryoperation) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func init() {
	proto.RegisterType((*Recoveryoperation)(nil), "tokenchain.loyalty.v1.Recoveryoperation")
}

func init() {
	proto.RegisterFile("tokenchain/loyalty/v1/recoveryoperation.proto", fileDescriptor_7cf1416d21b7f9ab)
}

var fileDescriptor_7cf1416d21b7f9ab = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x3f, 0x4e, 0xf3, 0x30,
	0x18, 0xc6, 0x9b, 0x7c, 0x6d, 0x3f, 0xe2, 0x14, 0x24, 0x2c, 0x40, 0x16, 0x12, 0xa1, 0xc0, 0xd2,
	0x85, 0x56, 0x15, 0x5c, 0x20, 0x3d, 0x42, 0x46, 0x96, 0xc8, 0x4d, 0xde, 0x8a, 0x88, 0xd4, 0x2e,
	0xf6, 0x9b, 0xaa, 0xb9, 0x05, 0xc7, 0x62, 0xec, 0xc8, 0x88, 0xda, 0x63, 0xb0, 0x20, 0x3b, 0x6e,
	0x40, 0x8c, 0xcf, 0xcf, 0xcf, 0x1f, 0x4b, 0x2f, 0xb9, 0x47, 0xf9, 0x02, 0x22, 0x7b, 0xe6, 0x85,
	0x98, 0x94, 0xb2, 0xe6, 0x25, 0xd6, 0x93, 0xf5, 0x74, 0xa2, 0x20, 0x93, 0x6b, 0x50, 0xb5, 0x5c,
	0x81, 0xe2, 0x58, 0x48, 0x31, 0x5e, 0x29, 0x89, 0x92, 0x9e, 0xff, 0xd8, 0xc7, 0xce, 0x3e, 0x5e,
	0x4f, 0x6f, 0xbf, 0x7c, 0x72, 0x9a, 0xfc, 0x8d, 0xd0, 0x13, 0xe2, 0x17, 0x39, 0xf3, 0x86, 0xde,
	0xa8, 0x9b, 0xf8, 0x45, 0x4e, 0xcf, 0x48, 0x2f, 0x07, 0x21, 0x97, 0xcc, 0x1f, 0x7a, 0xa3, 0x20,
	0x69, 0x04, 0xbd, 0x21, 0x83, 0x85, 0x92, 0xcb, 0x94, 0xe7, 0xb9, 0x02, 0xad, 0xd9, 0x3f, 0xfb,
	0x18, 0x1a, 0x16, 0x37, 0x88, 0x5e, 0x11, 0x82, 0xb2, 0x35, 0x74, 0xad, 0x21, 0x40, 0x79, 0x78,
	0xbe, 0x20, 0x7d, 0xbe, 0x94, 0x95, 0x40, 0xd6, 0xb3, 0x5b, 0x4e, 0x99, 0x66, 0x05, 0xaf, 0x15,
	0x68, 0x84, 0x3c, 0x9d, 0xd7, 0xac, 0xdf, 0x34, 0xb7, 0x6c, 0x56, 0xd3, 0x3b, 0x72, 0x0c, 0x1b,
	0xc8, 0x2a, 0x84, 0x94, 0x2f, 0x10, 0x14, 0xfb, 0x6f, 0x1b, 0x06, 0x0e, 0xc6, 0x86, 0x99, 0xf9,
	0x4c, 0x01, 0x37, 0x2d, 0x1c, 0xd9, 0x91, 0x75, 0x04, 0x8e, 0xc4, 0x68, 0xe6, 0x35, 0x72, 0xac,
	0x34, 0x0b, 0xec, 0x80, 0x53, 0xf4, 0x9a, 0x84, 0xae, 0xc6, 0xe6, 0x88, 0xcd, 0x91, 0x03, 0x8a,
	0xed, 0xff, 0x32, 0x2e, 0x32, 0x28, 0xcb, 0xc6, 0x11, 0x5a, 0x47, 0xd8, 0xb2, 0x18, 0xcd, 0xff,
	0x1a, 0x99, 0x2a, 0xe0, 0x5a, 0x0a, 0x36, 0xb0, 0x13, 0x2e, 0x97, 0x58, 0x36, 0x7b, 0x7c, 0xdf,
	0x45, 0xde, 0x76, 0x17, 0x79, 0x9f, 0xbb, 0xc8, 0x7b, 0xdb, 0x47, 0x9d, 0xed, 0x3e, 0xea, 0x7c,
	0xec, 0xa3, 0xce, 0xd3, 0xe5, 0xaf, 0xeb, 0x6e, 0xda, 0xfb, 0x62, 0xbd, 0x02, 0x3d, 0xef, 0xdb,
	0x8b, 0x3e, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xd5, 0xae, 0x99, 0x02, 0x02, 0x00, 0x00,
}

func (m *Recoveryoperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Recoveryoperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Recoveryoperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CancelReason) > 0 {
		i -= len(m.CancelReason)
		copy(dAtA[i:], m.CancelReason)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.CancelReason)))
		i--
		dAtA[i] = 0x62
	}
	if m.CancelledAt != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.CancelledAt))
		i--
		dAtA[i] = 0x58
	}
	if m.ExecutedAt != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.ExecutedAt))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.ExecuteAfter != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.ExecuteAfter))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequestedBy) > 0 {
		i -= len(m.RequestedBy)
		copy(dAtA[i:], m.RequestedBy)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.RequestedBy)))
		i--
		dAtA[i] = 0x32
	}
	if m.Amount != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRecoveryoperation(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRecoveryoperation(dAtA []byte, offset int, v uint64) int {
	offset -= sovRecoveryoperation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Recoveryoperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.Id))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.Amount))
	}
	l = len(m.RequestedBy)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	if m.ExecuteAfter != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.ExecuteAfter))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.CreatedAt))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	if m.ExecutedAt != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.ExecutedAt))
	}
	if m.CancelledAt != 0 {
		n += 1 + sovRecoveryoperation(uint64(m.CancelledAt))
	}
	l = len(m.CancelReason)
	if l > 0 {
		n += 1 + l + sovRecoveryoperation(uint64(l))
	}
	return n
}

func sovRecoveryoperation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRecoveryoperation(x uint64) (n int) {
	return sovRecoveryoperation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Recoveryoperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecoveryoperation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Recoveryoperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Recoveryoperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteAfter", wireType)
			}
			m.ExecuteAfter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteAfter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedAt", wireType)
			}
			m.ExecutedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelledAt", wireType)
			}
			m.CancelledAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelledAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CancelReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecoveryoperation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecoveryoperation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRecoveryoperation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRecoveryoperation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecoveryoperation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRecoveryoperation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRecoveryoperation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRecoveryoperation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRecoveryoperation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRecoveryoperation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRecoveryoperation = fmt.Errorf("proto: unexpected end of group")
)
