// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenchain/loyalty/v1/verifiedtoken.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Verifiedtoken defines the Verifiedtoken message.
type Verifiedtoken struct {
	Denom                 string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Issuer                string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Name                  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol                string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description           string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Website               string `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	MaxSupply             uint64 `protobuf:"varint,7,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	MintedSupply          uint64 `protobuf:"varint,8,opt,name=minted_supply,json=mintedSupply,proto3" json:"minted_supply,omitempty"`
	Verified              bool   `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	SeizureOptIn          bool   `protobuf:"varint,10,opt,name=seizure_opt_in,json=seizureOptIn,proto3" json:"seizure_opt_in,omitempty"`
	RecoveryGroupPolicy   string `protobuf:"bytes,11,opt,name=recovery_group_policy,json=recoveryGroupPolicy,proto3" json:"recovery_group_policy,omitempty"`
	RecoveryTimelockHours uint64 `protobuf:"varint,12,opt,name=recovery_timelock_hours,json=recoveryTimelockHours,proto3" json:"recovery_timelock_hours,omitempty"`
	Creator               string `protobuf:"bytes,13,opt,name=creator,proto3" json:"creator,omitempty"`
	AdminRenounced        bool   `protobuf:"varint,14,opt,name=admin_renounced,json=adminRenounced,proto3" json:"admin_renounced,omitempty"`
}

func (m *Verifiedtoken) Reset()         { *m = Verifiedtoken{} }
func (m *Verifiedtoken) String() string { return proto.CompactTextString(m) }
func (*Verifiedtoken) ProtoMessage()    {}
func (*Verifiedtoken) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d0e6c0dc00e30d, []int{0}
}
func (m *Verifiedtoken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Verifiedtoken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Verifiedtoken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Verifiedtoken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verifiedtoken.Merge(m, src)
}
func (m *Verifiedtoken) XXX_Size() int {
	return m.Size()
}
func (m *Verifiedtoken) XXX_DiscardUnknown() {
	xxx_messageInfo_Verifiedtoken.DiscardUnknown(m)
}

var xxx_messageInfo_Verifiedtoken proto.InternalMessageInfo

func (m *Verifiedtoken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Verifiedtoken) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *Verifiedtoken) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Verifiedtoken) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Verifiedtoken) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Verifiedtoken) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Verifiedtoken) GetMaxSupply() uint64 {
	if m != nil {
		return m.MaxSupply
	}
	return 0
}

func (m *Verifiedtoken) GetMintedSupply() uint64 {
	if m != nil {
		return m.MintedSupply
	}
	return 0
}

func (m *Verifiedtoken) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Verifiedtoken) GetSeizureOptIn() bool {
	if m != nil {
		return m.SeizureOptIn
	}
	return false
}

func (m *Verifiedtoken) GetRecoveryGroupPolicy() string {
	if m != nil {
		return m.RecoveryGroupPolicy
	}
	return ""
}

func (m *Verifiedtoken) GetRecoveryTimelockHours() uint64 {
	if m != nil {
		return m.RecoveryTimelockHours
	}
	return 0
}

func (m *Verifiedtoken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Verifiedtoken) GetAdminRenounced() bool {
	if m != nil {
		return m.AdminRenounced
	}
	return false
}

func init() {
	proto.RegisterType((*Verifiedtoken)(nil), "tokenchain.loyalty.v1.Verifiedtoken")
}

func init() {
	proto.RegisterFile("tokenchain/loyalty/v1/verifiedtoken.proto", fileDescriptor_d5d0e6c0dc00e30d)
}

var fileDescriptor_d5d0e6c0dc00e30d = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xc7, 0x1b, 0x6f, 0x6f, 0x6f, 0x7b, 0xfa, 0x21, 0x8c, 0x56, 0x87, 0x82, 0x21, 0xa8, 0x60,
	0xdd, 0xb4, 0x54, 0xc5, 0x07, 0x70, 0xa3, 0xae, 0x94, 0x28, 0x2e, 0xdc, 0x84, 0x34, 0x39, 0xda,
	0xa1, 0x99, 0x0f, 0x66, 0x26, 0xb1, 0xf1, 0x29, 0x7c, 0x2c, 0x97, 0x5d, 0x8a, 0x2b, 0x69, 0x5f,
	0x44, 0x32, 0xf9, 0xb8, 0xdd, 0xe5, 0xff, 0xff, 0xfd, 0x32, 0x1c, 0x0e, 0x07, 0x9e, 0x5b, 0xb9,
	0x47, 0x91, 0xec, 0x62, 0x26, 0xd6, 0x99, 0x2c, 0xe3, 0xcc, 0x96, 0xeb, 0x62, 0xb3, 0x2e, 0x50,
	0xb3, 0x6f, 0x0c, 0x53, 0x47, 0x57, 0x4a, 0x4b, 0x2b, 0xc9, 0xfc, 0x56, 0x5d, 0x35, 0xea, 0xaa,
	0xd8, 0x3c, 0xfe, 0x7b, 0x05, 0xd3, 0x2f, 0x97, 0x3a, 0xb9, 0x0f, 0xd7, 0x29, 0x0a, 0xc9, 0xa9,
	0x17, 0x78, 0xcb, 0x51, 0x58, 0x07, 0xf2, 0x00, 0x06, 0xcc, 0x98, 0x1c, 0x35, 0xbd, 0xe3, 0xea,
	0x26, 0x11, 0x02, 0x7d, 0x11, 0x73, 0xa4, 0x57, 0xae, 0x75, 0xdf, 0x95, 0x6b, 0x4a, 0xbe, 0x95,
	0x19, 0xed, 0xd7, 0x6e, 0x9d, 0x48, 0x00, 0xe3, 0x14, 0x4d, 0xa2, 0x99, 0xb2, 0x4c, 0x0a, 0x7a,
	0xed, 0xe0, 0x65, 0x45, 0x28, 0xdc, 0xfc, 0xc0, 0xad, 0x61, 0x16, 0xe9, 0xc0, 0xd1, 0x36, 0x92,
	0x47, 0x00, 0x3c, 0x3e, 0x44, 0x26, 0x57, 0x2a, 0x2b, 0xe9, 0x4d, 0xe0, 0x2d, 0xfb, 0xe1, 0x88,
	0xc7, 0x87, 0x4f, 0xae, 0x20, 0x4f, 0x60, 0xca, 0x99, 0xb0, 0x98, 0xb6, 0xc6, 0xd0, 0x19, 0x93,
	0xba, 0x6c, 0xa4, 0x05, 0x0c, 0xdb, 0xcd, 0xd0, 0x51, 0xe0, 0x2d, 0x87, 0x61, 0x97, 0xc9, 0x53,
	0x98, 0x19, 0x64, 0x3f, 0x73, 0x8d, 0x91, 0x54, 0x36, 0x62, 0x82, 0x82, 0x33, 0x26, 0x4d, 0xfb,
	0x41, 0xd9, 0xf7, 0x82, 0xbc, 0x80, 0xb9, 0xc6, 0x44, 0x16, 0xa8, 0xcb, 0xe8, 0xbb, 0x96, 0xb9,
	0x8a, 0x94, 0xcc, 0x58, 0x52, 0xd2, 0xb1, 0x9b, 0xf6, 0x5e, 0x0b, 0xdf, 0x56, 0xec, 0xa3, 0x43,
	0xe4, 0x35, 0x3c, 0xec, 0xfe, 0xb1, 0x8c, 0x63, 0x26, 0x93, 0x7d, 0xb4, 0x93, 0xb9, 0x36, 0x74,
	0xe2, 0x86, 0xec, 0x9e, 0xfc, 0xdc, 0xd0, 0x77, 0x15, 0xac, 0x76, 0x91, 0x68, 0x8c, 0xad, 0xd4,
	0x74, 0x5a, 0xef, 0xa2, 0x89, 0xe4, 0x19, 0xdc, 0x8d, 0x53, 0xce, 0x44, 0xa4, 0x51, 0xc8, 0x5c,
	0x24, 0x98, 0xd2, 0x99, 0x1b, 0x76, 0xe6, 0xea, 0xb0, 0x6d, 0xdf, 0xbc, 0xfa, 0x7d, 0xf2, 0xbd,
	0xe3, 0xc9, 0xf7, 0xfe, 0x9d, 0x7c, 0xef, 0xd7, 0xd9, 0xef, 0x1d, 0xcf, 0x7e, 0xef, 0xcf, 0xd9,
	0xef, 0x7d, 0x5d, 0x5c, 0x1c, 0xce, 0xa1, 0x3b, 0x1d, 0x5b, 0x2a, 0x34, 0xdb, 0x81, 0x3b, 0x98,
	0x97, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x35, 0x73, 0x59, 0xe5, 0x5d, 0x02, 0x00, 0x00,
}

func (m *Verifiedtoken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Verifiedtoken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Verifiedtoken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AdminRenounced {
		i--
		if m.AdminRenounced {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x6a
	}
	if m.RecoveryTimelockHours != 0 {
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(m.RecoveryTimelockHours))
		i--
		dAtA[i] = 0x60
	}
	if len(m.RecoveryGroupPolicy) > 0 {
		i -= len(m.RecoveryGroupPolicy)
		copy(dAtA[i:], m.RecoveryGroupPolicy)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.RecoveryGroupPolicy)))
		i--
		dAtA[i] = 0x5a
	}
	if m.SeizureOptIn {
		i--
		if m.SeizureOptIn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.MintedSupply != 0 {
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(m.MintedSupply))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxSupply != 0 {
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(m.MaxSupply))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintVerifiedtoken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerifiedtoken(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerifiedtoken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Verifiedtoken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	if m.MaxSupply != 0 {
		n += 1 + sovVerifiedtoken(uint64(m.MaxSupply))
	}
	if m.MintedSupply != 0 {
		n += 1 + sovVerifiedtoken(uint64(m.MintedSupply))
	}
	if m.Verified {
		n += 2
	}
	if m.SeizureOptIn {
		n += 2
	}
	l = len(m.RecoveryGroupPolicy)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	if m.RecoveryTimelockHours != 0 {
		n += 1 + sovVerifiedtoken(uint64(m.RecoveryTimelockHours))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovVerifiedtoken(uint64(l))
	}
	if m.AdminRenounced {
		n += 2
	}
	return n
}

func sovVerifiedtoken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerifiedtoken(x uint64) (n int) {
	return sovVerifiedtoken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Verifiedtoken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifiedtoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Verifiedtoken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Verifiedtoken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			m.MaxSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedSupply", wireType)
			}
			m.MintedSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintedSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeizureOptIn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeizureOptIn = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryGroupPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecoveryGroupPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryTimelockHours", wireType)
			}
			m.RecoveryTimelockHours = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveryTimelockHours |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminRenounced", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AdminRenounced = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipVerifiedtoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerifiedtoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerifiedtoken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerifiedtoken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifiedtoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerifiedtoken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerifiedtoken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerifiedtoken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerifiedtoken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerifiedtoken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerifiedtoken = fmt.Errorf("proto: unexpected end of group")
)
